# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd97316bfcaab41f14c62eaca5d48f4b8fb0e9f477aef8c3ed568b1278b48213735d426ffdee6ec96872b32ddf9da87cfaf753857d3dcdd436c4c566e70fd7b0

test:
  secret_key_base: ce097e2cd3a50cbfaca67da3a0b5466a0e2882cd2dd879e5b3e6a37c1527d98abe1adf80a05cba3a4960af5aa9288f07e13435a2a2bdd28e0dea2cb2173849fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
